# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4b2edd8c87f4c328fa8892258371cc836071469e1e4b5c331e720a68f6a9fec6839968638946388aed70d0843473c2eac7af7d1e6c3521a9c14d3fad1499c0

test:
  secret_key_base: 1ad82bb5360fc84a2ab116467bbb54b87cca2e9e06ef04540c68938a4b1ca2718c5a96ffe37fc3be843a29a4da46d1609866c3e3c2d894a9a0b0af31fa7529a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
